# Generated by Django 3.1.1 on 2020-09-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_1', models.CharField(max_length=100)),
                ('time_2', models.CharField(max_length=100)),
                ('placar_1', models.IntegerField(default=0)),
                ('placar_2', models.IntegerField(default=0)),
            ],
        ),
    ]
