# Generated by Django 3.1.1 on 2020-09-10 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200910_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='time_1',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='time_2',
        ),
        migrations.AddField(
            model_name='jogo',
            name='time1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time2', to='app.clube', unique=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='time2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time1', to='app.clube', unique=True),
        ),
        migrations.AlterField(
            model_name='clube',
            name='gols_pro',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='pontos',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='saldo_gols',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='vitorias',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_1',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_2',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
