# Generated by Django 3.1.1 on 2020-09-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200910_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='placar_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='placar_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='time1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time2', to='app.clube'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='time2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time1', to='app.clube'),
        ),
    ]
